apiVersion: v1
kind: BuildConfig
metadata:
  name: mavenapp-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent { label "maven" }
          environment {
            version = "1.0"
            devTag = "${version}-${BUILD_NUMBER}"
          }
          stages {
            stage("Clone Source") {
              steps {
                git url: "https://github.com/ishida330/SimpleJava.git", branch: "master"
              }
            }
            stage("Build Artifacts") {
              steps {
                sh "mvn package"
                stash includes: "target/Simple.war", name: "war"
              }
            }
            stage("Build Image") {
              steps {
                unstash "war"
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      def nb = openshift.selector("bc", "mavenapp")
                      nb.startBuild("--from-file=./target/Simple.war").logs("--follow")
                      def buildSelector = nb.narrow("bc").related("builds")
                      timeout(5) {
                        buildSelector.untilEach(1) {
                          return (it.object().status.phase == "Complete")
                        }
                      }
                      echo "Builds have been completed: ${buildSelector.names()}"
                    }
                  }
                }
              }
            }
            /*
            stage("Promote Image") {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      // Tag the mavenapp:latest image as mavenapp:${devTag}
                      openshift.tag("mavenapp:latest", "mavenapp:${devTag}")
                    }
                  }
                }
              }
            }
            */
          }
        }
    type: JenkinsPipeline
  triggers: []
  